name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

  # install:
  #   runs-on: ubuntu-latest
  #   needs: checkout
  #   steps:
      - name: Install dependencies
        run: |
              cd news-feed
              npm install
    
  # build:
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
      - name: Build project
        run: |
              cd news-feed
              npm run build
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
    # steps:
      - name: Deploy to github pages
        run: |
              cd news-feed
              git config --global user.email "kwshr96626@gmail.com"
              git config --global user.name "kawshar Patel"
              npm run deploy
    

